#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Formula1.Droid.Resource", IsApplication=true)]

namespace Formula1.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.CommunityToolkit.Resource.Id.cameratexture = global::Formula1.Droid.Resource.Id.cameratexture;
			global::Xamarin.CommunityToolkit.Resource.Layout.CameraFragment = global::Formula1.Droid.Resource.Layout.CameraFragment;
			global::Xamarin.CommunityToolkit.Resource.Style.MainTheme = global::Formula1.Droid.Resource.Style.MainTheme;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int calendar = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int driver = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int history = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int splash_background = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int splash_logo = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int splash_screen = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int team = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int welcome = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int cameratexture = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int CameraFragment = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int app_icon_adaptive_back = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_icon_adaptive_fore = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int icon = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int icon_round = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int launcher_foreground = 2131034116;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int MainTheme = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
